language: node_js

node_js: 16

script:
    - npm run lint
    - npm run test

before_deploy:
    - npm run build

deploy:
    - provider: npm
      skip_cleanup: true
      email: $npm_mail
      api_key: $npm_key
      on:
          tags: true
